# Generated by Django 3.2.10 on 2022-03-20 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
                ('photo', models.ImageField(upload_to='map/place/photo', verbose_name='写真')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='星')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.place', verbose_name='レビュー対象の投稿')),
            ],
        ),
    ]
